global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus 자체 메트릭
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastApi 애플리케이션의 메트릭 수집
  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi-app:8000']  # Docker Compose 서비스명 + 컨테이너 내부 포트

  # 시스템 메트릭 수집 (node-exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
